### PR TITLE
Updated to 1.19.1 and 1.19.2

### PR DESCRIPTION
**Pull request by rodis120**
Simple commit that adds support for versions 1.19.1 and 1.19.2.

### CODE REVIEW

**Comment by BananaPuncher714** [comment]
There is already support for 1.19.1.

**Comment by rodis120** [comment]
I compiled and tested plugin that is in your repo and it only works up 1.19. Newer versions throw error beacause the name of one of the functions has been changed.

**Comment by BananaPuncher714** [comment]
I have tested it for both versions 1.19.1 and 1.19.2 on Spigot. They function without error.

**Comment by BananaPuncher714** [comment]
Ok, it seems like I forgot to push my changes a while ago, so Github didn't reflect the support for 1.19.1. I also added 1.19.2 in the meantime, and tested it locally. Please build the master branch again and tell me if there are any errors. Thanks.

**Comment by rodis120** [comment]
I've just tested the plugin on 1.19.3 and everything seems to work without any errors. I will close my pull request now.

**Pull request closed without merging**
